distributable:
  url: https://github.com/eksctl-io/eksctl/archive/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: eksctl-io/eksctl

dependencies:
  github.com/kubernetes-sigs/aws-iam-authenticator: '*'

build:
  dependencies:
    go.dev: ~1.25
  script:
    - go build -trimpath -ldflags="-s -w -X github.com/eksctl-io/eksctl/v2/pkg/version.gitTag=v{{version}}" -o {{prefix}}/bin/eksctl ./cmd/eksctl

provides:
  - bin/eksctl

test: eksctl version | grep {{version}}
