distributable:
  url: git+https://github.com/mail-os/mail.git
  ref: v{{version}}

versions:
  github: mail-os/mail/tags
  strip: /^v/

provides:
  - bin/mail

build:
  dependencies:
    ziglang.org: 0.16.0-dev
    sqlite.org: '*'
  script:
    - zig build -Doptimize=ReleaseFast -p {{prefix}}
  working-directory: packages/zig

test:
  - '{{prefix}}/bin/mail --help'
