distributable:
  url: https://github.com/extrawurst/gitui/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

provides:
  - bin/gitui

versions:
  github: extrawurst/gitui/tags

dependencies:
  perl.org: '*'
  openssl.org: ^1.1
  zlib.net: ^1
  libgit2.org: ~1.7 # links to libgit2.so.1.7

build:
  dependencies:
    rust-lang.org: ^1.78 # stdsimd changes
    rust-lang.org/cargo: '*'
    cmake.org: 3 # as over 0.27.0
  script: cargo install --path . --locked --root {{prefix}}
  env:
    linux:
      RUSTFLAGS: '-C linker=cc'
      # See: https://docs.rs/openssl/latest/openssl/#manual
      OPENSSL_NO_VENDOR: true
      OPENSSL_DIR: /usr
      OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu
      OPENSSL_INCLUDE_DIR: /usr/include

test: gitui --version
