distributable:
  url: https://launchpad.net/libvterm/trunk/v{{version.marketing}}/+download/libvterm-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://launchpad.net/libvterm/+download
  match: /libvterm-\d+\.\d+\.\d+.tar.gz/
  strip:
    - /^libvterm-/
    - /\.tar\.gz$/

build:
  dependencies:
    gnu.org/libtool: '*'
  script:
    # GNU libtool from pantry provides 'libtool' but macOS Makefiles expect 'glibtool'
    - run: |
        if ! command -v glibtool &>/dev/null; then
          ln -sf "$(command -v libtool)" "$(dirname "$(command -v libtool)")/glibtool"
          ln -sf "$(command -v libtoolize)" "$(dirname "$(command -v libtoolize)")/glibtoolize"
        fi
      if: darwin
    - make --jobs {{ hw.concurrency }} install PREFIX="{{prefix}}"
provides:
  - bin/unterm
  - bin/vterm-ctrl
  - bin/vterm-dump

test:
  dependencies:
    freedesktop.org/pkg-config: '*'
  script:
    pkg-config --modversion vterm | grep {{version}}
