distributable:
  url: https://launchpad.net/libvterm/trunk/v{{version.marketing}}/+download/libvterm-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://launchpad.net/libvterm/+download
  match: /libvterm-\d+\.\d+\.\d+.tar.gz/
  strip:
    - /^libvterm-/
    - /\.tar\.gz$/

build:
  dependencies:
    gnu.org/libtool: '*'
  script:
    # macOS Makefiles expect 'glibtool' — use Homebrew's keg-only path
    - run: |
        if ! command -v glibtool &>/dev/null; then
          BREW_LIBTOOL="$(brew --prefix libtool 2>/dev/null)/bin"
          if [ -f "$BREW_LIBTOOL/glibtool" ]; then
            export PATH="$BREW_LIBTOOL:$PATH"
          fi
        fi
      if: darwin
    - make --jobs {{ hw.concurrency }} install PREFIX="{{prefix}}"
provides:
  - bin/unterm
  - bin/vterm-ctrl
  - bin/vterm-dump

test:
  dependencies:
    freedesktop.org/pkg-config: '*'
  script:
    pkg-config --modversion vterm | grep {{version}}
