distributable:
  url: https://ftpmirror.gnu.org/gnu/xorriso/xorriso-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  url: https://ftpmirror.gnu.org/gnu/xorriso/
  match: /xorriso-(\d+\.\d+\.\d+)\.tar\.gz/
  strip:
    - /xorriso-/
    - /.tar.gz/

dependencies:
  zlib.net: '*'
  sourceware.org/bzip2: '*'
  gnu.org/readline: '*'

build:
  dependencies:
    freedesktop.org/pkg-config: '*'
  script:
    - ./configure $ARGS
    - make --jobs {{ hw.concurrency }}
    - make install
  env:
    ARGS:
      - --prefix={{ prefix }}

provides:
  - bin/xorriso
  - bin/xorrisofs
  - bin/xorrecord
  - bin/osirrox

test:
  script: xorriso --version
