import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'deno.land',
  name: 'deno',
  description: 'A modern runtime for JavaScript and TypeScript.',
  homepage: 'https://deno.com/',
  github: 'https://github.com/denoland/deno',
  programs: ['deno'],
  versionSource: {
    type: 'github-releases',
    repo: 'denoland/deno',
  },
  distributable: {
    url: 'https://github.com/denoland/deno/archive/refs/tags/v{{ version }}.tar.gz',
    stripComponents: 1,
  },
  buildDependencies: {
    'llvm.org': '*',
    'rust-lang.org/rustup': '*',
    'git-scm.org': '2',
    'curl.se': '*',
    'cmake.org': '^3',
    'protobuf.dev': '*',
    'github.com/mikefarah/yq': '^4',
    'crates.io/semverator': '^0',
    'sourceware.org/libffi': '>=3.2.1',
  },

  build: {
    script: [
      'cd "cli/lib"',
      'echo -n "{{version}}" >version.txt',
      'cd "$HOME/.cargo/bin"',
      'ln -sf {{deps.rust-lang.org/rustup.prefix}}/bin/rustup .',
      'rustup default $(grep channel $SRCROOT/rust-toolchain.toml | sed \'s/channel = "//;s/"//\')',
      'ln -sf $HOME/.rustup/toolchains/*/bin/* .',
      'export FFI_VER=$(grep -A1 \'name = "libffi"\' Cargo.lock | sed -n -f $PROP)',
      'export FFI_SYS_VER=$(grep -A1 \'name = "libffi-sys"\' Cargo.lock | sed -n -f $PROP)',
      'cd "ext/ffi"',
      'cargo vendor third-party',
      'sed -i -f $PROP third-party/libffi-sys/build/not_msvc.rs',
      'sed -i \'s|libffi-sys = "\\(.*\\)"|libffi-sys = { version = "\\1", features = ["system"] }|\' Cargo.toml',
      'sed -i "s|libffi.workspace = true|libffi = \\"=${FFI_VER}\\"|" Cargo.toml',
      'sed -i "s|libffi-sys.workspace = true|libffi-sys = { version = \\"=${FFI_SYS_VER}\\", features = [\\"system\\"] }|" Cargo.toml',
      'EXTRA_ARGS="$EXTRA_ARGS --config patch.crates-io.libffi-sys.path=\'ext/ffi/third-party/libffi-sys\'"',
      'find ext/ffi/tinycc -maxdepth 0 -empty -exec \\',
      '  git clone https://github.com/TinyCC/tinycc.git {} \\;',
      '',
      'if test "{{hw.platform}}+{{ hw.arch }}" = "darwin+x86-64"; then',
      '  # our LLVM cannot build with deployment target set to 10.6',
      '  sed -i s/MACOSX_DEPLOYMENT_TARGET/\\#/ ext/ffi/tinycc/Makefile',
      'fi',
      '',
      'INSTALLER_RS=cli/tools/installer.rs',
      'INSTALLER_RS=cli/tools/installer/mod.rs',
      'sed -i -e \'s/home_path.push(".deno")/home_path.push(".local")/\' $INSTALLER_RS',
      'grep home_path $INSTALLER_RS',
      'sed -i -e \'s/version = "4.1.2"/version = "4.1.1"/\' -e \'s/0a677b8922c94e01bdbb12126b0bc852f00447528dee1782229af9c720c3f348/e89b8c6a2e4b1f45971ad09761aafb85514a84744b67a95e32c3cc1352d1f65c/\' Cargo.lock',
      'sed -i \'s/^version = .*/version = "{{version}}"/\' cli/Cargo.toml',
      'cargo install --locked --path cli --root "{{ prefix }}" $EXTRA_ARGS',
      'cargo install --locked --path cli/rt --root "{{ prefix }}" $EXTRA_ARGS',
    ],
    env: {
      'PATH': '$HOME/.cargo/bin:$PATH',
    },
  },
}
