import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'exiftool.org',
  name: 'exiftool',
  description: 'Perl lib for reading and writing EXIF metadata',
  homepage: 'https://exiftool.org',
  programs: ['exiftool'],
  distributable: {
    url: 'https://cpan.metacpan.org/authors/id/E/EX/EXIFTOOL/Image-ExifTool-{{version.raw}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'perl.org': '*',
  },
  buildDependencies: {
    'perl.org': '*',
  },

  build: {
    script: [
      '# Enable large file support',
      '# https://exiftool.org/forum/index.php?topic=3916.msg18182#msg18182',
      'sed -i.bak -e "s/LargeFileSupport => undef/LargeFileSupport => 1/" lib/Image/ExifTool.pm',
      'rm lib/Image/ExifTool.pm.bak',
      '',
      '# replace the hard-coded path to the lib directory',
      'sed -i.bak -e \'s|unshift @INC, $incDir;|unshift @INC, "$FindBin::Bin/../libexec/lib";|\' exiftool',
      'rm exiftool.bak',
      '',
      'sed -i.bak \'/^use strict;/i\\',
      'use FindBin;',
      '\' exiftool',
      'rm exiftool.bak',
      '',
      'perl Makefile.PL',
      'make all',
      '',
      'mkdir -p {{prefix}}/libexec',
      'mv lib {{prefix}}/libexec/',
      '',
      'mkdir -p {{prefix}}/bin',
      'mv exiftool {{prefix}}/bin/',
      'fix-shebangs.ts {{prefix}}/bin/*',
      '',
      'mkdir -p {{prefix}}/share/doc',
      'mv html/* {{prefix}}/share/doc/',
      '',
      'if [ -f blib/man1/exiftool.1 ]; then',
      '  mkdir -p {{prefix}}/share/man/man1',
      '  mv blib/man1/exiftool.1 {{prefix}}/share/man/man1/',
      'fi',
      '',
      'if [ -f blib/man3/File::RandomAccess.3 ]; then',
      '  mkdir -p {{prefix}}/share/man/man3',
      '  mv blib/man3/* {{prefix}}/share/man/man3/',
      'fi',
      '',
    ],
  },
}
