import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'llvm.org',
  name: 'llvm',
  description: 'The LLVM Project is a collection of modular and reusable compiler and toolchain technologies.',
  homepage: 'https://llvm.org',
  github: 'https://github.com/llvm/llvm-project',
  programs: ['lld', 'clang', 'clang++', 'cc', 'c++', 'cpp', 'nm', 'objcopy', 'ranlib', 'readelf', 'strings', 'strip', 'llvm-profdata', 'llvm-cov'],
  versionSource: {
    type: 'github-releases',
    repo: 'llvm/llvm-project',
    tagPattern: /^llvmorg-(.+)$/,
  },
  distributable: {
    url: 'https://github.com/llvm/llvm-project/releases/download/llvmorg-{{version}}/llvm-project-{{version}}.src.tar.xz',
    stripComponents: 1,
  },
  dependencies: {
    'zlib.net': '1',
    'facebook.com/zstd': '*',
  },
  buildDependencies: {
    'cmake.org': '>=3<3.29',
    'ninja-build.org': '1',
    'python.org': '>=3<3.12',
    'crates.io/semverator': '*',
  },

  build: {
    script: [
      'RUNTIMES="-DLLVM_ENABLE_RUNTIMES=\'compiler-rt\'"',
      'if test "{{hw.platform}}" = "linux"; then',
      '  ARGS="$ARGS $RUNTIMES"',
      'elif semverator satisfies \'>=14\' {{version}}; then',
      '  ARGS="$ARGS $RUNTIMES"',
      'elif test "{{hw.arch}}" = "x86-64" && semverator satisfies \'>=14\' {{version}}; then',
      '  ARGS="$ARGS $RUNTIMES"',
      'fi',
      '',
      'cmake ../llvm -G Ninja $ARGS',
      'ninja',
      'ninja install',
      'cd "${{prefix}}/bin"',
      'ln -sf clang cc',
      'ln -sf clang++ c++',
      'ln -sf clang-cpp cpp',
      'for x in nm objcopy ranlib readelf strings strip; do',
      '  ln -sf llvm-$x $x',
      'done',
      '',
      'cd "${{prefix}}/lib"',
      'TARGET="$(find . -maxdepth 1 -type d -name \\*-unknown-linux-gnu)"',
      'if test -n "$TARGET"; then',
      '  mv "$TARGET"/* .',
      '  rmdir "$TARGET"',
      '  ln -s . "$TARGET"',
      'fi',
      '',
    ],
    env: {
      'ARGS': ['-DCMAKE_INSTALL_PREFIX="{{prefix}}"', '-DCMAKE_BUILD_TYPE=Release', '-DLLVM_ENABLE_PROJECTS=\'lld;lldb;clang;clang-tools-extra\'', '-DLLVM_INCLUDE_DOCS=OFF', '-DLLVM_INCLUDE_TESTS=OFF', '-DLLVM_ENABLE_RTTI=ON', '-DLLVM_BUILD_LLVM_DYLIB=ON'],
    },
  },
}
