import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'logdy.dev',
  name: 'logdy',
  description: 'Web based real-time log viewer. Stream ANY content to a web UI with autogenerated filters. Parse any format with TypeScript.',
  homepage: 'https://logdy.dev',
  github: 'https://github.com/logdyhq/logdy-core',
  programs: ['logdy'],
  versionSource: {
    type: 'github-releases',
    repo: 'logdyhq/logdy-core',
  },
  distributable: {
    url: 'https://github.com/logdyhq/logdy-core/archive/refs/tags/{{version.tag}}.tar.gz',
    stripComponents: 1,
  },
  buildDependencies: {
    'go.dev': '^1.21.4',
  },

  build: {
    script: [
      'go build $ARGS -ldflags="$GO_LDFLAGS" ./',
    ],
    env: {
      'ARGS': ['-trimpath', '-o={{prefix}}/bin/logdy'],
      'GO_LDFLAGS': ['-s', '-w', '-X=main.Version={{version}}'],
    },
  },
}
