import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'mesa3d.org',
  name: 'mesa3d',
  programs: [],
  distributable: {
    url: 'https://mesa.freedesktop.org/archive/mesa-{{version}}.tar.xz',
    stripComponents: 1,
  },
  dependencies: {
    'libexpat.github.io': '*',
    'x.org/x11': '*',
    'x.org/xcb': '*',
    'x.org/xdamage': '*',
    'x.org/exts': '*',
    'invisible-island.net/ncurses': '*',
    'zlib.net': '*',
    'x.org/xrandr': '*',
  },
  buildDependencies: {
    'gnu.org/bison': '*',
    'mesonbuild.com': '*',
    'ninja-build.org': '*',
    'freedesktop.org/pkg-config': '*',
    'pygments.org': '*',
    'python.org': '~3.11',
    'x.org/protocol': '*',
    'github.com/westes/flex': '*',
    'llvm.org': '*',
  },

  build: {
    script: [
      'curl -L "$Mako" | tar zxf -',
      'curl -L "$MarkupSafe" | tar zxf -',
      'if test "{{hw.platform}}" = "linux"; then',
      '  MESON_ARGS="$MESON_ARGS -Ddri3=enabled -Dgallium-omx=disabled"',
      'fi',
      '',
      'if test "{{hw.platform}}" = "darwin"; then',
      '  MESON_ARGS="$MESON_ARGS -Dosmesa=true"',
      'fi',
      '',
      'cd "Mako-1.2.4"',
      'python -m venv venv',
      'source venv/bin/activate',
      'python setup.py install',
      'deactivate',
      'export PYTHONPATH=$PWD/venv/lib/python{{deps.python.org.version.marketing}}/site-packages/Mako-1.2.4-py3.11.egg:$PYTHONPATH',
      'export PATH=$PWD/venv/bin/mako-render:$PATH',
      'cd "MarkupSafe-2.1.2"',
      'python -m venv venv',
      'source venv/bin/activate',
      'python setup.py install',
      'deactivate',
      'cd venv/lib/python{{deps.python.org.version.marketing}}/site-packages',
      'EGG="$(echo MarkupSafe*)"',
      'export PYTHONPATH=$PWD/$EGG:$PYTHONPATH',
      'python -m venv venv',
      'source venv/bin/activate',
      'python -m pip install pyyaml',
      'deactivate',
      'export PYTHONPATH=$SRCROOT/venv/lib/python{{deps.python.org.version.marketing}}/site-packages:$PYTHONPATH',
      'meson setup build $MESON_ARGS',
      'meson compile -C build --verbose',
      'meson install -C build',
    ],
    env: {
      'Mako': 'https://files.pythonhosted.org/packages/05/5f/2ba6e026d33a0e6ddc1dddf9958677f76f5f80c236bd65309d280b166d3e/Mako-1.2.4.tar.gz',
      'MarkupSafe': 'https://files.pythonhosted.org/packages/95/7e/68018b70268fb4a2a605e2be44ab7b4dd7ce7808adae6c5ef32e34f4b55a/MarkupSafe-2.1.2.tar.gz',
      'PYTHONPATH': '{{deps.pygments.org.prefix}}/venv/lib/python{{deps.python.org.version.marketing}}/site-packages:$PYTHONPATH',
      'MESON_ARGS': ['--libdir=lib', '--prefix={{prefix}}', '--buildtype=release', '--wrap-mode=nofallback'],
    },
  },
}
