import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'opensearch.org',
  name: 'opensearch',
  description: '🔎 Open source distributed and RESTful search engine.',
  homepage: 'https://opensearch.org/docs/latest/opensearch/index/',
  github: 'https://github.com/opensearch-project/OpenSearch',
  programs: ['opensearch', 'opensearch-keystore', 'opensearch-plugin', 'opensearch-shard'],
  versionSource: {
    type: 'github-releases',
    repo: 'opensearch-project/OpenSearch',
  },
  distributable: {
    url: 'https://github.com/opensearch-project/OpenSearch/archive/refs/tags/{{version}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'openjdk.org': '^21',
    'openmp.llvm.org': '^19',
  },
  buildDependencies: {
    'cmake.org': '3',
    'git-scm.org': '*',
    'gnu.org/wget': '*',
    'gnu.org/gcc': '^11',
  },

  build: {
    script: [
      'if test "{{hw.platform}}+{{hw.arch}}" = "darwin+x86-64"; then',
      'sed -i \'s|JNAKernel32Library.getInstance();|//JNAKernel32Library.getInstance();|\' server/src/main/java/org/opensearch/bootstrap/Bootstrap.java',
      'fi',
      './gradlew -Dbuild.snapshot=false ":distribution:archives:no-jdk-{{hw.platform}}-tar:assemble"',
      'cd "${{prefix}}"',
      'tar --strip-components=1 -xf $SRCROOT/distribution/archives/no-jdk-{{hw.platform}}-tar/build/distributions/opensearch-*.tar.gz',
      'cd "${{prefix}}"',
      'if test "{{hw.platform}}+{{hw.arch}}" = "darwin+x86-64"; then',
      'rm -f lib/jna-*.jar',
      'fi',
      'cd "${{prefix}}/config"',
      'sed -i.bak "s|#\\s*cluster.name: .*|cluster.name: opensearch_pkgx|" opensearch.yml',
      'cd "k-NN"',
      'if [ -d .git ]; then',
      '  git fetch',
      'else',
      '  git clone https://github.com/opensearch-project/k-NN .',
      'fi',
      '',
      'git checkout {{version}}.0',
      'git reset --hard',
      'git submodule foreach --recursive git reset --hard',
      'git submodule update --init --recursive',
      'git config --global user.email "hello@pkgx.dev"',
      'git config --global user.name "pkgx"',
      'cd "k-NN/jni/external"',
      'if test "{{hw.platform}}+{{hw.arch}}" = "darwin+aarch64"; then',
      'sed -i -e \'s/-march=native/-mcpu=apple-m1/g\' nmslib/similarity_search/CMakeLists.txt',
      'sed -i -e \'s/-mcpu=apple-a14/-mcpu=apple-m1/g\' nmslib/python_bindings/setup.py',
      'sed -i -e \'s/__aarch64__/__undefine_aarch64__/g\' faiss/faiss/utils/distances_simd.cpp',
      'fi',
      'cd "k-NN"',
      'sed -i -f $PROP jni/CMakeLists.txt jni/cmake/*.cmake',
      'export CC=clang',
      'export CXX=clang++',
      'cd "k-NN/jni/external/nmslib/similarity_search"',
      'if test "{{hw.arch}}" = "x86-64"; then',
      '  sed -i.bak -e \'s/-march=native/-march=x86-64/g\' CMakeLists.txt',
      'fi',
      '',
      'cd "k-NN/jni"',
      'cmake . $CMAKE_ARGS',
      'make',
      'cd "k-NN/jni/release"',
      'for LIB in *.jnilib; do',
      '  install_name_tool -add_rpath @loader_path $LIB',
      'done',
      '',
      'cd "k-NN"',
      './gradlew build --refresh-dependencies -x integTest -x test -DskipTests=true -Dopensearch.version={{version}} -Dbuild.snapshot=false -Dbuild.version_qualifier=',
      './gradlew publishPluginZipPublicationToZipStagingRepository -Dopensearch.version={{version}} -Dbuild.snapshot=false -Dbuild.version_qualifier=',
      './gradlew publishPluginZipPublicationToMavenLocal -Dbuild.snapshot=false -Dbuild.version_qualifier= -Dopensearch.version={{version}}',
      'cd "k-NN"',
      'mkdir -p ./build/distributions/lib',
      'cp -v ./jni/release/libopensearchknn* ./build/distributions/lib',
      'cd ./build/distributions',
      'zip -r opensearch-knn-{{version}}.0.zip lib/',
      'TMP=$(mktemp -d /tmp/opensearch-knn-XXXXXX)',
      'rmdir $TMP',
      'ln -s {{prefix}} $TMP',
      '$TMP/bin/opensearch-plugin install --batch file:`pwd`/opensearch-knn-{{version}}.0.zip',
      'cd "${{prefix}}/bin"',
      'echo \'export JAVA_LIBRARY_PATH="$OPENSEARCH_HOME/plugins/opensearch-knn/lib:$JAVA_LIBRARY_PATH"\' >> opensearch-env',
      'cd "${{prefix}}/bin"',
      'echo \'export LD_LIBRARY_PATH="$OPENSEARCH_HOME/plugins/opensearch-knn/lib:$LD_LIBRARY_PATH"\' >> opensearch-env',
      'sed -i.bak \'1a\\',
      '# Auto-discover JAVA_HOME from java on PATH if not explicitly set\\',
      'if [ -z "$OPENSEARCH_JAVA_HOME" ] && [ -z "$JAVA_HOME" ]; then\\',
      '  _java_bin=$(command -v java 2>/dev/null)\\',
      '  if [ -n "$_java_bin" ]; then\\',
      '    _java_real=$(readlink -f "$_java_bin" 2>/dev/null || echo "$_java_bin")\\',
      '    export JAVA_HOME=$(cd "$(dirname "$_java_real")/.." && pwd)\\',
      '  fi\\',
      '  unset _java_bin _java_real\\',
      'fi\' "{{prefix}}/bin/opensearch-env" && rm -f "{{prefix}}/bin/opensearch-env.bak"',
    ],
  },
}
