import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'pcsclite.apdu.fr',
  name: 'pcsc-lite',
  programs: ['pcscd'],
  distributable: {
    url: 'https://pcsclite.apdu.fr/files/pcsc-lite-{{ version }}.tar.xz',
    stripComponents: 1,
  },
  dependencies: {
    'libusb.info': '^1',
  },
  buildDependencies: {
    'cmake.org': '^3',
    'mesonbuild.com': '^1',
    'ninja-build.org': '^1',
    'github.com/westes/flex': '*',
    'perl.org': '^5',
  },

  build: {
    script: [
      './configure $ARGS',
      'make install',
      '',
      'cd "build"',
      'meson setup . .. $MESON_ARGS',
      'meson compile --verbose',
      '',
      '# this tries to write to /sbin regardless of options;',
      '# so we do it by hand',
      '# meson install',
      '',
      'mkdir -p \'{{prefix}}\'/{bin,include,lib/pkgconfig,sbin,share/man/man{1,8}}',
      '',
      '# bin',
      'cp ../src/spy/pcsc-spy \'{{prefix}}/bin/pcscd-spy\'',
      '',
      '# include',
      'cp pcsclite.h ../src/PCSC/*.h \'{{prefix}}/include/\'',
      'ln -s . \'{{prefix}}/include/PCSC\'',
      '',
      '# lib',
      'if test "{{hw.platform}}" = "darwin"; then',
      '  cp libpcsc{lite,spy}.*dylib \'{{prefix}}/lib/\'',
      'else',
      '  cp libpcsc{lite,spy}.so{,.?} \'{{prefix}}/lib/\'',
      'fi',
      'cp meson-private/libpcsclite.pc \'{{prefix}}/lib/pkgconfig/\'',
      '',
      '# sbin',
      'cp pcscd \'{{prefix}}/sbin/pcscd\'',
      '',
      '# share',
      'cp ../pcsc-spy.1 \'{{prefix}}/share/man/man1/\'',
      'cp pcscd.8 \'{{prefix}}/share/man/man8/\'',
      '',
    ],
    env: {
      'ARGS': ['--disable-dependency-tracking', '--disable-silent-rules', '--prefix={{ prefix }}', '--sysconfdir=/etc', '--disable-polkit'],
      'MESON_ARGS': ['--prefix={{prefix}}', '--sbindir={{prefix}}/sbin', '--buildtype=release', '-Dpolkit=false'],
    },
  },
}
