import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'pip.pypa.io',
  name: 'pip',
  description: 'The Python package installer',
  homepage: 'https://pip.pypa.io/',
  github: 'https://github.com/pypa/pip',
  programs: ['pip', 'pip3.8', 'pip3.9', 'pip3.10', 'pip3.11'],
  versionSource: {
    type: 'github-releases',
    repo: 'pypa/pip/tags',
  },
  distributable: {
    url: 'https://github.com/pypa/pip/archive/refs/tags/{{version.raw}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'pkgx.sh': '>=1',
  },
  buildDependencies: {
    'python.org': '~3.11',
    'crates.io/semverator': '^0.4.3',
  },

  build: {
    script: [
      'pkgx curl -O https://bootstrap.pypa.io/get-pip.py',
      'rm -rf bootstrap && mkdir bootstrap',
      'python get-pip.py --target=bootstrap',
      'PYTHONPATH=$PWD/bootstrap python -m pip install . --target={{prefix}}/libexec',
      'v=3.7',
      'if semverator lt {{version}} 23.1.2; then',
      '  vMax=3.11',
      'else',
      '  vMax=3.12',
      'fi',
      '',
      'while semverator lt $v $vMax; do',
      'v=$(semverator bump $v minor | cut -d. -f1,2)',
      'install -D $PROP {{prefix}}/bin/pip$v',
      'echo "exec pkgx python@$v \\"\\$d/bin/pip\\" \\"\\$@\\"" >> {{prefix}}/bin/pip$v',
      '',
      'done',
      'install -D $PROP {{prefix}}/bin/pip3',
      'if semverator lt {{version}} 23.1.2; then',
      '  python="\'python<3.12\'"',
      'else',
      '  python=python@3',
      'fi',
      'echo "exec pkgx $python \\"\\$d/bin/pip\\" \\"\\$@\\"" >> {{prefix}}/bin/pip3',
      '',
      'install -D $PROP {{prefix}}/bin/pip',
      'if semverator lt {{version}} 23.1.2; then',
      '  python="\'python<3.12\'"',
      'else',
      '  python=python',
      'fi',
      'echo "exec pkgx $python \\"\\$d/bin/pip\\" \\"\\$@\\"" >> {{prefix}}/bin/pip',
      '',
      'rm {{prefix}}/libexec/bin/pip?*',
      'fix-shebangs.ts {{prefix}}/libexec/bin/*',
    ],
  },
}
