import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'python.org',
  name: 'python',
  description: 'The Python programming language',
  homepage: 'https://www.python.org',
  github: 'https://github.com/python/cpython',
  programs: ['python', 'python{{ version.major }}', 'python{{ version.marketing }}'],
  versionSource: {
    type: 'github-releases',
    repo: 'python/cpython/tags',
  },
  distributable: {
    url: 'https://www.python.org/ftp/python/{{ version.raw }}/Python-{{ version.raw }}.tar.xz',
    stripComponents: 1,
  },
  dependencies: {
    'zlib.net': '1',
    'sourceware.org/bzip2': '1',
    'openssl.org': '^1.1',
    'sourceware.org/libffi': '3',
    'libexpat.github.io': '2',
    'bytereef.org/mpdecimal': '2',
    'tukaani.org/xz': '5',
    'sqlite.org': '3',
    'gnu.org/readline': '8',
    'invisible-island.net/ncurses': '6',
    'facebook.com/zstd': '>=1.5',
  },
  buildDependencies: {
    'freedesktop.org/pkg-config': '^0.29',
    'gnu.org/patch': '*',
    'curl.se': '*',
  },

  build: {
    script: [
      'for PATCH in $PYTHON2PATCHES; do',
      '  curl -sSL $PATCH | patch -p0',
      'done',
      '',
      'sed -i.bak -e \'s|system_lib_dirs = .*|system_lib_dirs = os.getenv("LIBRARY_PATH").split(":")|\' ./setup.py',
      'sed -i.bak -e \'s|system_include_dirs = .*|system_include_dirs = os.getenv("CPATH").split(":")|\' ./setup.py',
      '',
      'confdir="$libdir/config"',
      '',
      '# aarch64 not happy with this',
      'ARGS=${ARGS/--with-ensurepip/--without-ensurepip}',
      '',
      'confdir=$(echo $confdir | sed -e \'s/\\(config-{{ version.marketing }}\\)/\\1m/\')',
      '',
      '# 3.7 and older use `python3.7m` for include dir',
      'SUFFIX=m',
      '',
      '# 3.7 aborts on linux+aarch64 with this',
      'ARGS=${ARGS/--with-ensurepip/--without-ensurepip}',
      '',
      'confdir="$libdir/config-{{version.marketing}}m"',
      'if test "{{hw.platform}}" = "darwin"; then',
      '  sed -i.bak \\',
      '      -e \'s/ppc)/arm64)/g\' \\',
      '      -e \'s/MACOSX_DEFAULT_ARCH="ppc.*$/MACOSX_DEFAULT_ARCH="arm64"/g\' \\',
      '      configure',
      '  rm configure.bak',
      'fi',
      '',
      'if test "{{hw.platform}}" = "darwin"; then',
      '  sed -i.bak -e \'s/^MULTIARCH=.*$/MULTIARCH=""/\' configure',
      '  rm configure.bak',
      'fi',
      '',
      'if test "{{hw.platform}}" = "darwin"; then',
      '  curl -L https://github.com/python/cpython/commit/8ea6353.patch | patch -p1',
      'fi',
      '',
      'patch -p1 < props/patch3.5.diff',
      'patch -p1 < props/patch3.4.diff',
      'sed -i.bak \'s/libmpdec_machine=universal/libmpdec_machine=x64/\' configure',
      'rm configure.bak',
      '',
      'sed -i.bak \'s/libmpdec_machine=universal/libmpdec_machine=uint128/\' configure',
      'rm configure.bak',
      '',
      './configure $ARGS',
      'make --jobs {{ hw.concurrency }}',
      'make install',
      'cp props/sitecustomize.py {{prefix}}/lib/python{{version.marketing}}',
      'cd "${{prefix}}/bin"',
      'for x in python idle pydoc; do',
      '  ln -sf ${x}{{ version.marketing }} $x',
      'done',
      'ln -sf python{{ version.marketing }}-config python-config',
      '',
      'cd "${{prefix}}/bin"',
      'find . -mindepth 1 -maxdepth 1 -type f -name \'pip*\' -exec rm {} \\;',
      'cd "${{prefix}}"',
      'for binfile in $shebangs $confdir/python-config.py; do',
      '  if ! test -f $binfile; then',
      '    binfile=${binfile/{{version.marketing}}/{{version.marketing}}$SUFFIX}',
      '  fi',
      '  if ! test -f $binfile; then',
      '    continue',
      '  fi',
      '  binfile=$(readlink -f $binfile)',
      '  sed -i.bak -e \'s|#!{{ prefix }}/bin/|#!/usr/bin/env |g\' $binfile',
      '  rm $binfile.bak',
      'done',
      '',
      'sed -i.bak -e \'s|{{ prefix }}|\\\\$(or $(PKGX_DIR),$(HOME)/.pkgx)/python.org/v{{version.major}}|g\' $confdir/Makefile',
      'rm $confdir/Makefile.bak',
      '',
      'cd "${{prefix}}/lib/python{{version.marketing}}"',
      'cat $PROP >> _sysconfigdata__*.py',
      'ln -s /dev {{prefix}}/lib/python{{version.marketing}}/site-packages',
      'cd "${{prefix}}/include"',
      'mv python{{version.marketing}}$SUFFIX/* .',
      'rmdir python{{version.marketing}}$SUFFIX',
      'ln -s . python{{version.marketing}}',
      '# Keep the suffixed version if we started with one',
      'if test -n "$SUFFIX"; then',
      '  ln -s . python{{version.marketing}}$SUFFIX',
      'fi',
      '',
    ],
    env: {
      'ARGS': ['--prefix="{{ prefix }}"', '--with-ensurepip', '--enable-ipv6', '--disable-loadable-sqlite-extensions', '--with-system-expat', '--with-system-ffi', '--with-system-libmpdec', '--enable-shared'],
      'libdir': 'lib/python{{version.marketing}}',
      'shebangs': ['bin/2to3-{{version.marketing}}', 'bin/idle{{version.marketing}}', 'bin/pydoc{{version.marketing}}', 'bin/python{{version.marketing}}-config'],
      'CPPFLAGS': '${CPPFLAGS:+$CPPFLAGS }-I{{ deps.zlib.net.prefix }}/include',
      'LDFLAGS': '${LDFLAGS:+$LDFLAGS }-L{{ deps.zlib.net.prefix }}/lib',
      'OPENSSL_INCLUDES': '${{ deps.openssl.org.prefix }}/include',
      'OPENSSL_LDFLAGS': '-L{{ deps.openssl.org.prefix }}/lib',
      'PYTHON2PATCHES': ['https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-Makefile.pre.in.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-setup.py.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-Lib-cgi.py.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-Lib-ctypes-macholib-dyld.py.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-configure.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-libedit.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/enable-loadable-sqlite-extensions.patch', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/patch-_osx_support.py.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/darwin20.diff', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/arm.patch', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/implicit.patch', 'https://raw.githubusercontent.com/macports/macports-ports/master/lang/python27/files/openssl_ver.patch'],
    },
  },
}
