import type { RecipeDefinition } from '../../scripts/recipe-types'

export const recipe: RecipeDefinition = {
  domain: 'rubygems.org',
  name: 'rubygems',
  description: 'Powerful, clean, object-oriented scripting language',
  homepage: 'https://www.ruby-lang.org/',
  github: 'https://github.com/ruby/ruby',
  programs: ['bundle', 'bundler', 'gem'],
  versionSource: {
    type: 'github-releases',
    repo: 'rubygems/rubygems',
  },
  distributable: {
    url: 'https://github.com/rubygems/rubygems/archive/refs/tags/v{{version}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'ruby-lang.org': '>=2.3',
  },
  buildDependencies: {
    'ruby-lang.org': '<4',
  },

  build: {
    script: [
      'ruby setup.rb --prefix={{prefix}} --env-shebang --no-ri --no-rdoc',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < $PROP',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/fit-n-finish.patch',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/fit-n-finish2-pre357.patch',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/fit-n-finish2-post357.patch',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/default-sys-dir.patch',
      'sed -i -e \'s/Gem.default_dir/Gem.default_system_dir/\' lib/rubygems/path_support.rb',
      '',
      'cd "${{prefix}}/lib/rubygems"',
      'sed -i -e \'s/Gem.state_home, "gem",/Gem.state_home,/\' defaults.rb',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/user-install-pre3.5.patch',
      'cd "${{prefix}}"',
      'patch -p1 --no-backup-if-mismatch < "$SRCROOT"/props/user-install-post3.5.patch',
      'cd "${{prefix}}/lib/rubygems"',
      'sed -i -e \'s/Dir\\.mkdir dir, \\*\\[options\\[:dir_mode\\].*/FileUtils.mkdir_p dir, *[options[:dir_mode] \\&\\& 0o755].compact/\' installer.rb',
      'cd "${{prefix}}/bin"',
      'for PROG in rake rbs rdbg typeprof; do if test -f $PROG; then rm $PROG; fi; done',
      'cd "${{prefix}}"',
      'for tool in bundle bundler; do',
      '  echo "$(cat $PROP gems/bundler-*/exe/$tool)" > bin/$tool',
      'done',
      'echo "$(cat $PROP bin/gem)" > bin/gem',
      '',
      'cd "${{prefix}}/lib/rubygems"',
      'sed -i -f $PROP installer.rb',
      'rm -rf {{prefix}}/gems',
      'cd "${{prefix}}"',
      'ln -s bin exe',
      'rm -rf {{prefix}}/plugins',
    ],
  },
}
