import type { Recipe } from '../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'systemd.io',
  name: 'systemd',
  description: 'The systemd System and Service Manager ',
  homepage: 'https://systemd.io',
  github: 'https://github.com/systemd/systemd',
  programs: ['busctl', 'coredumpctl', 'hostnamectl', 'journalctl', 'kernel-install', 'localectl', 'loginctl', 'machinectl', 'networkctl', 'oomctl', 'portablectl', 'resolvectl', 'systemctl', 'systemd-ac-power', 'systemd-analyze', 'systemd-ask-password', 'systemd-cat', 'systemd-cgls', 'systemd-cgtop', 'systemd-confext', 'systemd-creds', 'systemd-delta', 'systemd-detect-virt', 'systemd-dissect', 'systemd-escape', 'systemd-firstboot', 'systemd-id128', 'systemd-inhibit', 'systemd-machine-id-setup', 'systemd-mount', 'systemd-notify', 'systemd-nspawn', 'systemd-path', 'systemd-repart', 'systemd-resolve', 'systemd-run', 'systemd-socket-activate', 'systemd-stdio-bridge', 'systemd-sysext', 'systemd-sysusers', 'systemd-tmpfiles', 'systemd-tty-ask-password-agent', 'systemd-umount', 'timedatectl', 'udevadm', 'userdbctl', 'halt', 'init', 'mount.ddi', 'poweroff', 'reboot', 'resolvconf', 'runlevel', 'shutdown', 'telinit'],
  platforms: ['linux'],
  versionSource: {
    type: 'github-releases',
    repo: 'systemd/systemd',
  },
  distributable: {
    url: 'https://github.com/systemd/systemd/archive/refs/tags/{{version.tag}}.tar.gz',
    stripComponents: 1,
  },
  dependencies: {
    'libexpat.github.io': '*',
    'google.com/fullycapable': '*',
    'lz4.org': '*',
    'openssl.org': '^1.1',
    'github.com/util-linux/util-linux': '*',
    'tukaani.org/xz': '*',
    'facebook.com/zstd': '*',
    'github.com/besser82/libxcrypt': '*',
    'curl.se': '*',
    'gnu.org/libidn2': '*',
    'gnutls.org': '*',
    'sourceware.org/bzip2': '*',
    'pcre.org/v2': '*',
  },
  buildDependencies: {
    'gnu.org/coreutils': '*',
    'docbook.org': '*',
    'gnu.org/gettext': '*',
    'gnu.org/gperf': '*',
    'github.com/mattrobenolt/jinja2-cli': '*',
    'gnupg.org/libgpg-error': '*',
    'gnu.org/libtool': '*',
    'gnome.org/libxslt': '*',
    'gnome.org/libxml2': '~2.13',
    'gnu.org/m4': '*',
    'mesonbuild.com': '*',
    'ninja-build.org': '*',
    'freedesktop.org/pkg-config': '*',
    'python.org': '>=3<3.12',
    'rsync.samba.org': '*',
  },

  build: {
    script: [
      'cd "src/basic"',
      'sed -i -f $PROP process-util.h',
      'meson setup $ARGS build',
      'meson compile -C build',
      'meson install -C build',
      'cd "{{prefix}}/lib"',
      'if test -d systemd; then',
      '  ln -s systemd/lib* .',
      'fi',
      '',
    ],
    env: {
      'ARGS': ['--sysconfdir={{prefix}}/etc', '--localstatedir={{prefix}}/var', '-Dprefix={{prefix}}', '-Dsysvinit-path={{prefix}}/etc/init.d', '-Dsysvrcnd-path={{prefix}}/etc/rc.d', '-Dpamconfdir={{prefix}}/etc/pam.d', '-Dcreate-log-dirs=false', '-Dhwdb=false', '-Dlz4=enabled', '-Dgcrypt=disabled', '-Dmode=release'],
    },
  },
}
