distributable:
  url: https://github.com/dyne/frei0r/archive/refs/tags/v{{version}}.tar.gz
  strip-components: 1

versions:
  github: dyne/frei0r

build:
  dependencies:
    cmake.org: '*'
  script: |
    # Disable opportunistic linking against Cairo
    sed -i.bak -e "s/find_package (Cairo)//" CMakeLists.txt
    rm CMakeLists.txt.bak
    cmake . $ARGS
    make install
  env:
    ARGS:
      - -DCMAKE_INSTALL_PREFIX="{{prefix}}"
      - -DCMAKE_BUILD_TYPE=Release
      - -DWITHOUT_OPENCV=ON
      - -DWITHOUT_GAVL=ON

test:
  script: |
    cc test.c -o test
    ./test
