import type { Recipe } from '../../../scripts/recipe-types'

export const recipe: Recipe = {
  domain: 'gnu.org/coreutils',
  name: 'coreutils',
  programs: [
    '[',
    'b2sum',
    'base32',
    'base64',
    'basename',
    'basenc',
    'cat',
    'chgrp',
    'chmod',
    'chown',
    'chroot',
    'cksum',
    'comm',
    'cp',
    'csplit',
    'cut',
    'date',
    'dd',
    'df',
    'dir',
    'dircolors',
    'dirname',
    'du',
    'echo',
    'env',
    'expand',
    'expr',
    'factor',
    'false',
    'fmt',
    'fold',
    'groups',
    'head',
    'hostid',
    'id',
    'install',
    'join',
    'kill',
    'link',
    'ln',
    'logname',
    'ls',
    'md5sum',
    'mkdir',
    'mkfifo',
    'mknod',
    'mktemp',
    'mv',
    'nice',
    'nl',
    'nohup',
    'nproc',
    'numfmt',
    'od',
    'paste',
    'pathchk',
    'pinky',
    'pr',
    'printenv',
    'printf',
    'ptx',
    'pwd',
    'readlink',
    'realpath',
    'rm',
    'rmdir',
    'seq',
    'sha1sum',
    'sha224sum',
    'sha256sum',
    'sha384sum',
    'sha512sum',
    'shred',
    'shuf',
    'sleep',
    'sort',
    'split',
    'stat',
    'stty',
    'sum',
    'sync',
    'tac',
    'tail',
    'tee',
    'test',
    'timeout',
    'touch',
    'tr',
    'true',
    'truncate',
    'tsort',
    'tty',
    'uname',
    'unexpand',
    'uniq',
    'unlink',
    'uptime',
    'users',
    'vdir',
    'wc',
    'who',
    'whoami',
    'yes',
  ],
  distributable: {
    url: 'https://ftp.gnu.org/gnu/coreutils/coreutils-{{ version.raw }}.tar.gz',
    stripComponents: 1,
  },
  build: {
    script: [
      {
        run: 'export ARGS="$ARGS --enable-install-program=kill,uptime"',
        if: '>=3.9.0',
      },
      './configure --prefix={{ prefix }} $ARGS',
      'make --jobs {{ hw.concurrency }} install',
    ],
    env: {
      FORCE_UNSAFE_CONFIGURE: '1',
    },
  },
  test: {
    script: [
      'touch test-file',
      'test "$(ls -1)" = "test-file"',
    ],
  },
}
