distributable:
  url: https://download.savannah.gnu.org/releases/lzip/lzip-{{version.marketing}}.tar.gz
  strip-components: 1

versions:
  url: https://download.savannah.gnu.org/releases/lzip/
  match: /lzip-\d+\.\d+\.tar\.gz/
  strip:
    - /^lzip-/
    - /.tar.gz$/

build:
  script: |
    ./configure $ARGS
    make --jobs {{ hw.concurrency }}
    make install
  env:
    ARGS:
      - --prefix="{{prefix}}"

provides:
  - bin/lzip

test: lzip --version | grep {{version.marketing}}
