distributable:
  url: https://github.com/pimalaya/himalaya/archive/refs/tags/{{ version.tag }}.tar.gz
  strip-components: 1

provides:
  - bin/himalaya

versions:
  github: pimalaya/himalaya

build:
  dependencies:
    rust-lang.org: '>=1.85'
    rust-lang.org/cargo: '*'
  script: |
    # Source pins rust-toolchain.toml to 1.82, but deps (imap-types) need 1.85+
    rm -f rust-toolchain.toml
    rustup default stable
    cargo install --path . --root {{prefix}}

test:
  - run: test "$(himalaya --version)" = "himalaya {{version}}"
    if: <1
  - run: himalaya --version | grep "himalaya v{{version}}"
    if: '>=1'
