distributable: ~

warnings: [vendored]

versions:
  github: meilisearch/meilisearch
  strip: /^v/

build:
  dependencies:
  script:
    - curl -L "$DIST" -o meilisearch
    - chmod +x meilisearch
    - mkdir -p "{{prefix}}/bin"
    - mv meilisearch "{{prefix}}/bin/"
  env:
    darwin/aarch64:
      DIST: https://github.com/meilisearch/meilisearch/releases/download/v{{version}}/meilisearch-macos-apple-silicon
    darwin/x86-64:
      DIST: https://github.com/meilisearch/meilisearch/releases/download/v{{version}}/meilisearch-macos-amd64
    linux/aarch64:
      DIST: https://github.com/meilisearch/meilisearch/releases/download/v{{version}}/meilisearch-linux-aarch64
    linux/x86-64:
      DIST: https://github.com/meilisearch/meilisearch/releases/download/v{{version}}/meilisearch-linux-amd64

provides:
  - bin/meilisearch

test:
  script:
    - meilisearch --version | grep {{version}}
