distributable:
  url: https://github.com/laravel/installer/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: laravel/installer

dependencies:
  php.net: ^8.2
  getcomposer.org: ^2.7
  darwin:
    unicode.org: ^78 # PHP's ICU libs need libicudata in the same dir

companions:
  linux:
    info-zip.org/unzip: ^6
    gnu.org/sed: "*" # needed to edit new deploys at run time

build:
  # 5.11.1 shipped as 5.11.0
  - run: perl -pi -e "s/'Laravel Installer', '[0-9\.]+'/'Laravel Installer', '{{version}}'/" laravel
    working-directory: bin
  # PHP's ICU libs use @loader_path but libicudata isn't in the PHP tarball
  - run: |
      for lib in {{deps.unicode.org.prefix}}/lib/libicu*.dylib; do
        [ -f "$lib" ] && ln -sf "$lib" {{deps.php.net.prefix}}/lib/ 2>/dev/null || true
      done
    if: darwin
  - composer install --no-dev
  - mkdir -p {{prefix}}/libexec
  - cp -r ./* {{prefix}}/libexec
  - run: ln -s ../libexec/bin/laravel laravel
    working-directory: ${{prefix}}/bin
  # patch installer so `laravel new` projects pass LD_LIBRARY_PATH to `artisan serve`
  - run: sed -i -f $PROP NewCommand.php
    prop: |
      /\$process.*runCommands.*isSuccessful/a\
                  $this->replaceInFile("'PATH',", "'PATH',\\n        'LD_LIBRARY_PATH',", "$directory/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php");
    if: linux
    working-directory: ${{prefix}}/libexec/src

provides:
  - bin/laravel

test:
  dependencies:
    curl.se: "*"
    pkgx.sh: ">=1"
  script:
    - laravel --version
    - laravel --version | grep {{version}}
    - laravel new blog --no-interaction
    - run:
        - (php artisan serve --port=$PORT & echo $! > server.pid) | tee server.log &
        - sleep 15
        - curl -s http://localhost:$PORT | tee out
        - kill $(cat server.pid)
        - grep Laravel out
        - grep 'Server running' server.log
      working-directory: blog
  env:
    PORT: $(pkgx pkgx^1 get-port | tail -n1)
