distributable:
  url: https://github.com/laravel/installer/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: laravel/installer

dependencies:
  php.net: ^8.2
  getcomposer.org: ^2.7

companions:
  linux:
    info-zip.org/unzip: ^6
    gnu.org/sed: "*" # needed to edit new deploys at run time

build:
  # 5.11.1 shipped as 5.11.0
  - run: perl -pi -e "s/'Laravel Installer', '[0-9\.]+'/'Laravel Installer', '{{version}}'/" laravel
    working-directory: bin
  # PHP's ICU libs use @loader_path but libicudata isn't in the PHP tarball.
  # Rewrite PHP's ICU references to use Homebrew's ICU and symlink libs.
  - run: |
      brew install icu4c 2>/dev/null || true
      ICU_LIB="$(brew --prefix icu4c)/lib"
      PHP_LIB="{{deps.php.net.prefix}}/lib"
      if [ -d "$ICU_LIB" ] && [ -d "$PHP_LIB" ]; then
        for lib in "$ICU_LIB"/libicu*.dylib; do
          [ -f "$lib" ] && ln -sf "$lib" "$PHP_LIB/" 2>/dev/null || true
        done
        # Rewrite @loader_path refs in PHP's ICU libs to use Homebrew's paths
        for phplib in "$PHP_LIB"/libicu*.dylib; do
          [ -L "$phplib" ] && continue
          [ -f "$phplib" ] || continue
          for iculib in "$ICU_LIB"/libicu*.dylib; do
            base="$(basename "$iculib")"
            install_name_tool -change "@loader_path/$base" "$iculib" "$phplib" 2>/dev/null || true
          done
        done
      fi
    if: darwin
  - composer install --no-dev
  - mkdir -p {{prefix}}/libexec
  - cp -r ./* {{prefix}}/libexec
  - run: ln -s ../libexec/bin/laravel laravel
    working-directory: ${{prefix}}/bin
  # patch installer so `laravel new` projects pass LD_LIBRARY_PATH to `artisan serve`
  - run: sed -i -f $PROP NewCommand.php
    prop: |
      /\$process.*runCommands.*isSuccessful/a\
                  $this->replaceInFile("'PATH',", "'PATH',\\n        'LD_LIBRARY_PATH',", "$directory/vendor/laravel/framework/src/Illuminate/Foundation/Console/ServeCommand.php");
    if: linux
    working-directory: ${{prefix}}/libexec/src

provides:
  - bin/laravel

test:
  dependencies:
    curl.se: "*"
    pkgx.sh: ">=1"
  script:
    - laravel --version
    - laravel --version | grep {{version}}
    - laravel new blog --no-interaction
    - run:
        - (php artisan serve --port=$PORT & echo $! > server.pid) | tee server.log &
        - sleep 15
        - curl -s http://localhost:$PORT | tee out
        - kill $(cat server.pid)
        - grep Laravel out
        - grep 'Server running' server.log
      working-directory: blog
  env:
    PORT: $(pkgx pkgx^1 get-port | tail -n1)
