distributable:
  url: https://gstreamer.freedesktop.org/src/orc/orc-{{version}}.tar.xz
  strip-components: 1

versions:
  url: https://gstreamer.freedesktop.org/src/orc/
  match: /orc-\d+\.\d+\.\d+\.tar\.xz/
  strip:
    - /^orc-/
    - /\.tar\.xz$/

build:
  dependencies:
    mesonbuild.com: "*"
    ninja-build.org: "*"
  working-directory: build
  script:
    - run: export ARGS="$(echo $ARGS | sed s'/gtk_doc/hotdoc/')"
      if: ">=0.4.42"
    # On darwin, pantry's meson wrapper may have SyntaxError — find system meson
    - run: |
        SYSMESON=""
        for p in /opt/homebrew/bin/meson /usr/local/bin/meson; do
          if [ -x "$p" ] && "$p" --version &>/dev/null; then
            SYSMESON="$p"; break
          fi
        done
        if [ -n "$SYSMESON" ]; then
          "$SYSMESON" $ARGS ..
        else
          meson $ARGS ..
        fi
      if: darwin
    - run: meson $ARGS ..
      if: linux
    - ninja -v
    - ninja install -v
  env:
    ARGS:
      - --prefix="{{prefix}}"
      - --libdir="{{prefix}}/lib"
      - --buildtype=release
      - --wrap-mode=nofallback
      - -Dgtk_doc=disabled

provides:
  - bin/orcc
  - bin/orc-bugreport

test:
  dependencies:
    freedesktop.org/pkg-config: "*"
  script: pkg-config --modversion orc-{{version.marketing}} | grep {{version}}
