distributable:
  url: https://gstreamer.freedesktop.org/src/orc/orc-{{version}}.tar.xz
  strip-components: 1

versions:
  url: https://gstreamer.freedesktop.org/src/orc/
  match: /orc-\d+\.\d+\.\d+\.tar\.xz/
  strip:
    - /^orc-/
    - /\.tar\.xz$/

build:
  dependencies:
    mesonbuild.com: "*"
    ninja-build.org: "*"
  working-directory: build
  script:
    - run: export ARGS="$(echo $ARGS | sed s'/gtk_doc/hotdoc/')"
      if: ">=0.4.42"
    # On darwin, S3 meson wrapper is broken — install via pip3 and fix it
    - run: |
        pip3 install --break-system-packages meson 2>/dev/null || pip3 install meson
        printf '#!/usr/bin/env python3\nfrom mesonbuild.mesonmain import main\nmain()\n' > "$(which meson)"
        chmod +x "$(which meson)"
        meson setup $ARGS ..
      if: darwin
    - run: meson $ARGS ..
      if: linux
    - ninja -v
    - ninja install -v
  env:
    ARGS:
      - --prefix="{{prefix}}"
      - --libdir="{{prefix}}/lib"
      - --buildtype=release
      - --wrap-mode=nofallback
      - -Dgtk_doc=disabled

provides:
  - bin/orcc
  - bin/orc-bugreport

test:
  dependencies:
    freedesktop.org/pkg-config: "*"
  script: pkg-config --modversion orc-{{version.marketing}} | grep {{version}}
