# Example GitHub Actions Workflow for OIDC Publishing
#
# This workflow demonstrates how to publish packages using OIDC authentication
# with Pantry. It includes best practices for security and reliability.
#
# Features:
# - OIDC authentication (no NPM_TOKEN needed)
# - Environment protection
# - Automated testing before publish
# - SLSA provenance generation
# - Multi-registry support

name: Publish Package with OIDC

on:
  # Trigger on release creation
  release:
    types: [created]

  # Manual trigger with version input
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to publish (e.g., 1.0.0)'
        required: true
        type: string

# OIDC requires id-token: write permission
permissions:
  id-token: write   # Required for OIDC token
  contents: read    # Required to checkout code
  packages: write   # Required for GitHub Packages (optional)

# Use environment for additional protection
# Configure at: Settings > Environments > production
# Add required reviewers for extra security
env:
  NODE_VERSION: '20'

jobs:
  # Job 1: Run tests before publishing
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm test

      - name: Run integration tests
        run: npm run test:integration

      - name: Build package
        run: npm run build

      - name: Test build artifacts
        run: |
          if [ ! -d "dist" ]; then
            echo "Build failed: dist directory not found"
            exit 1
          fi

  # Job 2: Publish to npm using OIDC
  publish-npm:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: test
    environment: production  # Requires approval if configured
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Install Pantry
        run: |
          curl -fsSL https://pantry.sh/install | bash
          echo "$HOME/.pantry/bin" >> $GITHUB_PATH

      - name: Verify Pantry installation
        run: pantry --version

      - name: Publish to npm registry with OIDC
        run: |
          echo "Publishing package using OIDC authentication..."
          pantry publish \
            --registry https://registry.npmjs.org \
            --provenance

      - name: Upload provenance attestation
        uses: actions/upload-artifact@v4
        with:
          name: provenance-npm
          path: '*.provenance.json'
          if-no-files-found: warn

  # Job 3: Publish to GitHub Packages (optional)
  publish-github:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: test
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@${{ github.repository_owner }}'

      - name: Install dependencies
        run: npm ci

      - name: Build package
        run: npm run build

      - name: Update package.json for GitHub Packages
        run: |
          # Update package name to include scope for GitHub Packages
          node -e "
            const pkg = require('./package.json');
            if (!pkg.name.startsWith('@${{ github.repository_owner }}/')) {
              pkg.name = '@${{ github.repository_owner }}/' + pkg.name.replace(/^@[^/]+\//, '');
            }
            pkg.publishConfig = { registry: 'https://npm.pkg.github.com' };
            require('fs').writeFileSync('package.json', JSON.stringify(pkg, null, 2));
          "

      - name: Install Pantry
        run: |
          curl -fsSL https://pantry.sh/install | bash
          echo "$HOME/.pantry/bin" >> $GITHUB_PATH

      - name: Publish to GitHub Packages with OIDC
        run: |
          echo "Publishing to GitHub Packages..."
          pantry publish \
            --registry https://npm.pkg.github.com \
            --provenance

      - name: Upload provenance attestation
        uses: actions/upload-artifact@v4
        with:
          name: provenance-github
          path: '*.provenance.json'
          if-no-files-found: warn

  # Job 4: Create GitHub Release with Artifacts
  create-release-assets:
    name: Attach Artifacts to Release
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-github]
    if: github.event_name == 'release'
    permissions:
      contents: write
    steps:
      - name: Download provenance artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: provenance-*
          merge-multiple: true

      - name: Attach provenance to release
        uses: softprops/action-gh-release@v1
        with:
          files: '*.provenance.json'

  # Job 5: Notify on Success
  notify:
    name: Notify Publication
    runs-on: ubuntu-latest
    needs: [publish-npm, publish-github]
    if: always()
    steps:
      - name: Check job status
        id: check
        run: |
          if [ "${{ needs.publish-npm.result }}" == "success" ] || [ "${{ needs.publish-github.result }}" == "success" ]; then
            echo "status=success" >> $GITHUB_OUTPUT
          else
            echo "status=failure" >> $GITHUB_OUTPUT
          fi

      - name: Success notification
        if: steps.check.outputs.status == 'success'
        run: |
          echo "✅ Package published successfully!"
          echo "Published by: ${{ github.actor }}"
          echo "Workflow: ${{ github.workflow }}"
          echo "Ref: ${{ github.ref }}"

      - name: Failure notification
        if: steps.check.outputs.status == 'failure'
        run: |
          echo "❌ Package publication failed"
          exit 1

# Optional: Slack/Discord webhook notifications
# - name: Notify Slack
#   if: steps.check.outputs.status == 'success'
#   uses: slackapi/slack-github-action@v1
#   with:
#     webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
#     payload: |
#       {
#         "text": "Package ${{ github.repository }} published successfully!"
#       }
