distributable:
  url: https://www.agwa.name/projects/git-crypt/downloads/git-crypt-{{version}}.tar.gz
  strip-components: 1

versions:
  url: https://www.agwa.name/projects/git-crypt/
  match: /git-crypt-\d+\.\d+\.\d+\.tar\.gz/
  strip:
    - /^git-crypt-/
    - /\.tar\.gz$/

dependencies:
  openssl.org: '^1.1'

build:
  script:
    - make ENABLE_MAN=no PREFIX={{prefix}} install
  env:
    CFLAGS: $CFLAGS -DOPENSSL_API_COMPAT=0x30000000L

provides:
  - bin/git-crypt

test:
  - git-crypt keygen keyfile
  - ls | grep keyfile
  - git-crypt version | grep {{version}}
