// Auto-generated package index
// Do not edit this file directly

export interface Pantry {
}

export type Packages = Pantry

export const pantry: Pantry = {
}

export const packages: Packages = pantry
