distributable:
  url: https://github.com/rclone/rclone/archive/v{{version}}.tar.gz
  strip-components: 1
versions:
  github: rclone/rclone
build:
  dependencies:
    go.dev: '*'
  script:
    - go build $ARGS -ldflags='-s -w -X github.com/rclone/rclone/fs.Version=v{{version}}'
  env:
    CGO_ENABLED: 0
    ARGS:
      - -trimpath
      - -o={{prefix}}/bin/rclone
provides:
  - bin/rclone
test:
  script:
    - echo "My version - {{version}}" > test.txt
    - rclone copy test.txt dist
    - cat dist/test.txt | grep {{version}}
    - rclone --version | grep {{version}}
