//! Developer/debugging commands

const std = @import("std");
const io_helper = @import("../../io_helper.zig");
const lib = @import("../../lib.zig");
const common = @import("common.zig");
const style = @import("../style.zig");

const CommandResult = common.CommandResult;
const string = lib.string;

// Note: the live `dev:shellcode` integration is generated by
// `src/shell/generator.zig` from `src/shell/templates/shell_integration.sh`
// (wired via `shellCodeCommand`). A second, divergent shellcode generator used
// to live here; it was never routed by the CLI and has been removed to keep a
// single source of truth for the shell hook.

/// Dev: MD5 command - compute MD5 hash of a file or stdin
pub fn devMd5Command(allocator: std.mem.Allocator, path: []const u8) !CommandResult {
    const is_stdin = std.mem.eql(u8, path, "/dev/stdin");

    var hasher = std.crypto.hash.Md5.init(.{});

    if (is_stdin) {
        // Read from stdin (Zig 0.15 API)
        const stdin_file = std.io.getStdIn();
        var buf: [4096]u8 = undefined;
        while (true) {
            const bytes_read = try stdin_file.read(&buf);
            if (bytes_read == 0) break;
            hasher.update(buf[0..bytes_read]);
        }
    } else {
        // Read from file
        const file = io_helper.cwd().openFile(io_helper.io, path, .{}) catch |err| {
            const msg = try std.fmt.allocPrint(
                allocator,
                "Error: Failed to open file {s}: {}",
                .{ path, err },
            );
            return .{
                .exit_code = 1,
                .message = msg,
            };
        };
        defer file.close(io_helper.io);

        var buf: [4096]u8 = undefined;
        while (true) {
            const bytes_read = try file.read(&buf);
            if (bytes_read == 0) break;
            hasher.update(buf[0..bytes_read]);
        }
    }

    var digest: [16]u8 = undefined;
    hasher.final(&digest);

    // Convert to hex string
    const hex = try string.hashToHex(digest, allocator);
    defer allocator.free(hex);

    style.print("{s}\n", .{hex});

    return .{ .exit_code = 0 };
}

/// Dev: find-project-root command - find project root from a directory
pub fn devFindProjectRootCommand(allocator: std.mem.Allocator, start_dir: []const u8) !CommandResult {
    const detector = @import("../../deps/detector.zig");

    // Try to find a dependency file
    const deps_file = (try detector.findDepsFile(allocator, start_dir)) orelse {
        // No project found
        return .{ .exit_code = 1 };
    };
    defer allocator.free(deps_file.path);

    // Get the directory of the dependency file
    const project_dir = std.fs.path.dirname(deps_file.path) orelse start_dir;

    style.print("{s}\n", .{project_dir});

    return .{ .exit_code = 0 };
}

/// Dev: check-updates command - check for newer pantry version
/// Called in background by shell integration. Writes update info to ~/.pantry/.update-available
pub fn devCheckUpdatesCommand(allocator: std.mem.Allocator) !CommandResult {
    const version_options = @import("version");
    const current_version = version_options.version;

    // Determine update marker file path
    const home = io_helper.getEnvVarOwned(allocator, "HOME") catch {
        return .{ .exit_code = 0 };
    };
    defer allocator.free(home);

    const marker_path = try std.fmt.allocPrint(allocator, "{s}/.pantry/.update-available", .{home});
    defer allocator.free(marker_path);

    // Check if we already checked recently (within 24 hours)
    if (io_helper.statFile(marker_path)) |stat| {
        const now_ts = io_helper.clockGettime();
        const now_sec: i128 = @intCast(now_ts.sec);
        const now_ns: i128 = now_sec * 1_000_000_000;
        const file_age_ns = now_ns - stat.mtime;
        const one_day_ns: i128 = 86400 * 1_000_000_000;
        if (file_age_ns < one_day_ns) {
            // Checked less than 24 hours ago, skip
            return .{ .exit_code = 0 };
        }
    } else |_| {}

    // Query npm registry for latest pantry version
    const registry_url = "https://registry.npmjs.org/pantry-cli/latest";
    const response = io_helper.httpGet(allocator, registry_url) catch {
        // Network error - silently skip (this is a background check)
        return .{ .exit_code = 0 };
    };
    defer allocator.free(response);

    // Parse JSON response to get version field
    const parsed = std.json.parseFromSlice(std.json.Value, allocator, response, .{}) catch {
        return .{ .exit_code = 0 };
    };
    defer parsed.deinit();

    if (parsed.value != .object) return .{ .exit_code = 0 };

    const version_val = parsed.value.object.get("version") orelse return .{ .exit_code = 0 };
    if (version_val != .string) return .{ .exit_code = 0 };

    const latest_version = version_val.string;

    // Compare versions - if different and latest is newer, write marker
    if (!std.mem.eql(u8, current_version, latest_version)) {
        // Ensure ~/.pantry directory exists
        const pantry_dir = try std.fmt.allocPrint(allocator, "{s}/.pantry", .{home});
        defer allocator.free(pantry_dir);
        io_helper.makePath(pantry_dir) catch {};

        // Write the latest version to the marker file
        const file = io_helper.createFile(marker_path, .{ .truncate = true }) catch {
            return .{ .exit_code = 0 };
        };
        defer io_helper.closeFile(file);
        io_helper.writeAllToFile(file, latest_version) catch {};
    } else {
        // Up to date - remove marker if it exists
        io_helper.deleteFile(marker_path) catch {};
    }

    return .{ .exit_code = 0 };
}
