distributable:
  # GNU bc uses zero-padded minor versions (1.07.1, 1.08.2) but semver normalizes
  # them (1.7.1, 1.8.2). Reconstruct the padded format for the download URL.
  url: https://ftpmirror.gnu.org/gnu/bc/bc-{{version.major}}.0{{version.minor}}.{{version.patch}}.tar.gz
  strip-components: 1

versions:
  url: https://ftpmirror.gnu.org/gnu/bc/
  match: /bc-\d+\.\d+\.\d+\.tar\.gz/
  strip:
    - /^bc-/
    - /\.tar\.gz$/

dependencies:
  github.com/westes/flex: ^2.6

build:
  dependencies:
    gnu.org/bison: '*'
    gnu.org/ed: '*'
    linux:
      gnu.org/texinfo: '*'
  script:
    - ./configure $ARGS
    # this tries to add `-ledit` to the list of targets on darwin
    - run: "sed 's/^\\(\\$(PROGRAMS): \\$(LDADD)\\)$/# \\1/' Makefile > Makefile.tmp && mv Makefile.tmp Makefile"
      working-directory: dc
      if: '>=1.8'
    - make --jobs {{hw.concurrency}} install
  env:
    ARGS:
      - --disable-debug
      - --disable-dependency-tracking
      - --disable-silent-rules
      - --prefix={{prefix}}
      - --infodir={{prefix}}/share/info
      - --mandir={{prefix}}/share/man
      - --with-libedit

provides:
  - bin/bc
  - bin/dc

test:
  - bc --version | grep {{version.raw}}
  - echo '150+150' | bc | grep 300
  - dc --version | grep {{version.raw}}
  - run: test "$(dc -f $FIXTURE)" = 300
    fixture: |
      150 150 +
      p
