name: pantry Installer
description: Install packages using pantry in GitHub Actions
author: Stacks.js
branding:
  icon: package
  color: blue

inputs:
  packages:
    description: Space-separated list of packages to install (overrides auto-detection)
    required: false
    default: ''
  config-path:
    description: Path to pantry config file
    required: false
    default: pantry.config.ts

runs:
  using: node16
  main: dist/index.js
