distributable:
  url: https://github.com/zeromq/libzmq/releases/download/v{{version}}/zeromq-{{version}}.tar.gz
  strip-components: 1

versions:
  github: zeromq/libzmq/releases/tags

build:
  script: |
    ./configure $ARGS
    make --jobs {{hw.concurrency}} install
  env:
    ARGS:
      - --disable-Werror # fails to build due to deprecations
      - --disable-debug
      - --prefix={{prefix}}
      - --without-docs

test:
  dependencies:
    freedesktop.org/pkg-config: '*'
  script: |
    cc fixture.c -lzmq
    ./a.out
    pkg-config libzmq --cflags
    pkg-config libzmq --libs
