distributable:
  url: https://github.com/madler/zlib/archive/refs/tags/v{{version.raw}}.tar.gz
  strip-components: 1

versions:
  github: madler/zlib
  strip: /^v/

# dependencies:
#   zlib.net: '*'

build:
  dependencies:
    gnu.org/autoconf: ^2
    gnu.org/automake: ^1
    gnu.org/libtool: ^2
    # zlib.net: '*'
  script:
    # macOS Makefiles expect 'glibtool' — use Homebrew's keg-only path
    - run: |
        if ! command -v glibtool &>/dev/null; then
          BREW_LIBTOOL="$(brew --prefix libtool 2>/dev/null)/bin"
          if [ -f "$BREW_LIBTOOL/glibtool" ]; then
            export PATH="$BREW_LIBTOOL:$PATH"
          fi
        fi
      if: darwin
    - run: |
        cd contrib/minizip
        autoreconf -fi
        ./configure --prefix={{prefix}}
        make install

test: cc test.c -o test -lminizip -lz
