distributable:
  url: https://ftpmirror.gnu.org/gnu/texinfo/texinfo-{{ version.raw }}.tar.gz
  strip-components: 1

versions:
  url: https://ftpmirror.gnu.org/gnu/texinfo/
  match: /texinfo-(\d+\.\d+(\.\d+)?)\.tar\.gz/
  strip:
    - /texinfo-/
    - /.tar.gz/

dependencies:
  perl.org: ~5.42 # requires stable minor; must match gettext's perl

build:
  dependencies:
    gnu.org/gettext: "*"
    invisible-island.net/ncurses: "*"
  script:
    - ./configure --prefix={{ prefix }}
    - make --jobs {{ hw.concurrency }} install

    - run: |
        for f in pod2texi texi2any makeinfo; do
          if [ -f "$f" ]; then
            perl -pi -e 's|^#!.*/perl|#!/usr/bin/env perl|' "$f"
          fi
        done
        head makeinfo
      working-directory: ${{prefix}}/bin

test:
  script:
    - makeinfo $FIXTURE
    - grep -q 'Hello World!' $(basename $FIXTURE).info
  fixture: |
    @ifnottex
    @node Top
    @top Hello World!
    @end ifnottex
    @bye

provides:
  - bin/info
  - bin/install-info
  - bin/makeinfo
  - bin/pdftexi2dvi
  - bin/pod2texi
  - bin/texi2any
  - bin/texi2dvi
  - bin/texi2pdf
  - bin/texindex
