distributable:
  url: https://github.com/syncthing/syncthing/archive/refs/tags/{{version.tag}}.tar.gz
  strip-components: 1

versions:
  github: syncthing/syncthing

build:
  dependencies:
    go.dev: ^1.21
  script:
    # Patch compat.yaml to support newer Go versions not yet listed upstream
    - run: |
        if [ -f compat.yaml ] && ! grep -q 'go1.26' compat.yaml; then
          printf '\n- runtime: go1.26\n  requirements:\n    darwin: "21"\n    linux: "3.2"\n    windows: "10.0"\n' >> compat.yaml
        fi
    - go run build.go --version {{version.tag}} --no-upgrade tar
    - install -D syncthing {{prefix}}/bin/syncthing
    - run: cp $SRCROOT/man/*.1 ./
      working-directory: ${{prefix}}/share/man/man1
    - run: cp $SRCROOT/man/*.5 ./
      working-directory: ${{prefix}}/share/man/man5
    - run: cp $SRCROOT/man/*.7 ./
      working-directory: ${{prefix}}/share/man/man7

provides:
  - bin/syncthing

test:
  - run:
      - syncthing --version | grep {{version}}
      - syncthing -generate ./
    if: <2
  - run:
      - syncthing version | grep {{version}}
      - syncthing generate -H .
    if: '>=2'
  - test -f config.xml
