distributable:
  url: https://github.com/strace/strace/releases/download/v{{version.raw}}/strace-{{version.raw}}.tar.xz
  strip-components: 1

versions:
  github: strace/strace/releases/tags

platforms: linux

build:
  script: |
    ./configure $ARGS
    make --jobs {{hw.concurrency}} install
  env:
    # Define BTRFS_EXTENT_REF_V0_KEY removed in newer kernel headers (6.x+)
    CFLAGS: "-DBTRFS_EXTENT_REF_V0_KEY=176"
    ARGS:
      - --disable-dependency-tracking
      - --disable-silent-rules
      - --enable-mpers=no # FIX: configure: error: Cannot enable m32 personality support
      - --prefix="{{prefix}}"
      - --disable-gcc-Werror

provides:
  - bin/strace

test: strace true 2>&1
