name: Build Zig Binaries

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/zig/**'
      - '.github/workflows/build-zig.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/zig/**'
      - '.github/workflows/build-zig.yml'
  release:
    types: [created]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Run tests
        working-directory: packages/zig
        run: zig build test

  build:
    name: Build ${{ matrix.target }}
    needs: test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: macos-aarch64
            os: macos-latest
            zig_target: aarch64-macos
          - target: macos-x86_64
            os: macos-latest
            zig_target: x86_64-macos
          - target: linux-aarch64
            os: ubuntu-latest
            zig_target: aarch64-linux
          - target: linux-x86_64
            os: ubuntu-latest
            zig_target: x86_64-linux
          # Windows disabled until platform-specific issues are resolved
          # - target: windows-x86_64
          #   os: ubuntu-latest
          #   zig_target: x86_64-windows

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout zonfig dependency
        uses: actions/checkout@v4
        with:
          repository: stacksjs/zonfig
          path: zonfig

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build for ${{ matrix.target }}
        working-directory: packages/zig
        run: zig build compile-all

      - name: Verify binary
        working-directory: packages/zig
        run: |
          ls -lh zig-out/bin/${{ matrix.target }}/pantry
          file zig-out/bin/${{ matrix.target }}/pantry

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pantry-${{ matrix.target }}
          path: packages/zig/zig-out/bin/${{ matrix.target }}/pantry
          retention-days: 30

  release:
    name: Create Release
    needs: build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: binaries

      - name: Create checksums
        run: |
          cd binaries
          for dir in pantry-*; do
            cd "$dir"
            sha256sum pantry > pantry.sha256
            cd ..
          done

      - name: Upload release assets
        uses: softprops/action-gh-release@v1
        with:
          files: |
            binaries/pantry-*/pantry
            binaries/pantry-*/pantry.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
