name: Lint Zig Code

on:
  push:
    branches: [main, develop]
    paths:
      - 'packages/zig/**'
      - '.github/workflows/lint-zig.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/zig/**'
      - '.github/workflows/lint-zig.yml'

jobs:
  format-check:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Check formatting
        working-directory: packages/zig
        run: |
          echo "Checking Zig code formatting..."
          zig fmt --check src/
          zig fmt --check test/
          zig fmt --check bench/
          zig fmt --check build.zig

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout zonfig dependency
        uses: actions/checkout@v4
        with:
          repository: stacksjs/zonfig
          path: zonfig

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Build (compile check)
        working-directory: packages/zig
        run: |
          echo "Running compile check..."
          zig build --summary all

      - name: Run static analysis
        working-directory: packages/zig
        run: |
          echo "Checking for common issues..."
          # Check for unused variables (zig build will catch these)
          zig build 2>&1 | tee build.log

          # Fail if there are warnings
          if grep -q "warning:" build.log; then
            echo "Build warnings found:"
            grep "warning:" build.log
            exit 1
          fi

  verify-cross-compilation:
    name: Verify Cross-Compilation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Checkout zonfig dependency
        uses: actions/checkout@v4
        with:
          repository: stacksjs/zonfig
          path: zonfig

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.15.1

      - name: Verify cross-compilation setup
        working-directory: packages/zig
        run: |
          echo "Verifying cross-compilation targets..."
          # This will build all targets (except Windows which has known issues)
          zig build compile-all || true

          # Verify at least the Linux and macOS binaries were created
          if [ ! -f zig-out/bin/linux-x86_64/pantry ]; then
            echo "Error: Linux x86_64 binary not created"
            exit 1
          fi

          if [ ! -f zig-out/bin/macos-aarch64/pantry ]; then
            echo "Error: macOS ARM64 binary not created"
            exit 1
          fi

          echo "Cross-compilation verification passed!"
